name: Chạy bot Zalo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout mã nguồn
        uses: actions/checkout@v3

      - name: Cài đặt Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cài đặt thư viện
        run: pip install -r requirements.txt

      - name: Chạy bot
        run: python bot.py
