name: Run Bot

on:
  push:
    branches:
      - main  # Hoặc tên nhánh mà bạn muốn theo dõi, ví dụ: 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Chọn phiên bản Python bạn cần

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Cài đặt các thư viện cần thiết

    - name: Run bot
      run: |
        python bot.py  # Chạy bot của bạn
