name: Run Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Check out mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Cài đặt các thư viện từ requirements.txt
      - name: Install dependencies
        run: |
          pip install -r ngan/requirements.txt

      # Kiểm tra nội dung thư mục
      - name: List files in 'ngan' directory
        run: |
          echo "Listing files in 'ngan' directory..."
          ls -l ngan

      # Kiểm tra xem Python có thể chạy
      - name: Check Python version
        run: |
          python3 --version

      # Kiểm tra lại các module cần thiết
      - name: Check if necessary modules are installed
        run: |
          pip list

      # Kiểm tra môi trường trước khi chạy
      - name: Test if bot script is executable
        run: |
          echo "Testing bot script execution..."
          ls -l ngan/main.py
          head -n 20 ngan/main.py

      # Chạy bot và capture output
      - name: Run bot and capture output
        run: |
          echo "Running bot..."
          python3 ngan/main.py || echo "Bot execution failed with exit code $?"
