name: Run Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Check out mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Cài đặt các thư viện từ requirements.txt
      - name: Install dependencies
        run: |
          pip install -r ngan/requirements.txt

      # Kiểm tra nội dung thư mục
      - name: List files in 'ngan' directory
        run: |
          echo "Listing files in 'ngan' directory..."
          ls -l ngan

      # Chạy bot
      - name: Run bot
        run: |
          echo "Running bot..."
          python3 ngan/main.py
