name: Run Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Check out mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Cài đặt các thư viện từ requirements.txt
      - name: Install dependencies
        run: |
          pip install -r ngan/requirements.txt

      # Kiểm tra nội dung thư mục
      - name: List files in 'ngan' directory
        run: |
          echo "Listing files in 'ngan' directory..."
          ls -l ngan

      # Chạy bot và ghi lỗi (nếu có)
      - name: Run bot
        run: |
          echo "Running bot..."
          python3 ngan/main.py || { echo "Bot failed to run"; exit 1; }

      # In ra các lỗi Python (nếu có)
      - name: Display Python error logs
        run: |
          echo "Displaying Python error logs..."
          tail -n 10 ngan/bot_error.log || echo "No error log found"
