name: Run Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      # Check out mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Cài đặt các thư viện từ requirements.txt
      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          pip install -r ngan/requirements.txt 2>&1 | tee result.log || { echo 'Failed to install dependencies!'; exit 1; }

      # Kiểm tra nội dung thư mục
      - name: List files in 'ngan' directory
        run: |
          echo "Listing files in 'ngan' directory..."
          ls -l ngan 2>&1 | tee -a result.log

      # Kiểm tra xem Python có thể chạy
      - name: Check Python version
        run: |
          echo "Checking Python version..."
          python3 --version 2>&1 | tee -a result.log || { echo 'Python version check failed!'; exit 1; }

      # Kiểm tra lại các module cần thiết
      - name: Check if necessary modules are installed
        run: |
          echo "Checking installed Python packages..."
          pip list 2>&1 | tee -a result.log || { echo 'Failed to list Python packages!'; exit 1; }

      # Kiểm tra môi trường trước khi chạy
      - name: Test if bot script is executable
        run: |
          echo "Testing bot script execution..."
          ls -l ngan/main.py 2>&1 | tee -a result.log || { echo 'Bot script not found or not executable!'; exit 1; }
          head -n 20 ngan/main.py 2>&1 | tee -a result.log || { echo 'Failed to read bot script!'; exit 1; }

      # Chạy bot và capture output
      - name: Run bot and capture output
        run: |
          echo "Running bot..."
          python3 ngan/main.py 2>&1 | tee -a result.log || { 
            echo 'Bot execution failed with exit code $?'; 
            tail -n 20 result.log;
            exit 1;
          }


      # In log ra khi bot thất bại
      - name: Print bot execution log
        if: failure()
        run: |
          echo "Bot execution failed. Showing full log..."
          cat result.log
