name: Run Bot Workflow

on:
  push:
    branches:
      - main

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      # Check out mã nguồn
      - name: Checkout repository
        uses: actions/checkout@v2

      # Cài đặt Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Cài đặt các thư viện từ requirements.txt
      - name: Install dependencies
        run: |
          pip install -r ngan/requirements.txt

      # Hoặc thêm các câu lệnh khác để kiểm tra môi trường
      - name: Run bot
        run: python ngan/main.py


      # In ra nội dung thư mục để kiểm tra xem file có đúng không
      - name: List files
        run: |
          echo "Listing files..."
          ls -l ngan
